name: Deploy XianCraft

# This workflow is triggered when code is pushed to the 'master' branch.
on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('''**/Cargo.lock''') }}

      - name: Build Rust application
        run: |
          source "$HOME/.cargo/env"
          cargo build --release --verbose

      - name: Deploy
        run: |
          echo "Deploying application and data to /srv/xiancraft..."
          mkdir -p /srv/xiancraft
          
          echo "Copying application binary..."
          cp "${GITHUB_WORKSPACE}/target/release/server" /srv/xiancraft/server
          
          echo "Copying game data directory..."
          cp -r "${GITHUB_WORKSPACE}/data" /srv/xiancraft/
          
          echo "Restarting service..."
          sudo systemctl restart xiancraft.service
